use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

#[path = "src/rig/release_metadata.rs"]
mod release_metadata;

const R_VERSION_METADATA_PATH: &str = "src/rig/r-versions.json";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/rig/release_metadata.rs");
    println!("cargo:rerun-if-changed={R_VERSION_METADATA_PATH}");

    let json = fs::read_to_string(R_VERSION_METADATA_PATH)
        .unwrap_or_else(|e| panic!("failed to read `{R_VERSION_METADATA_PATH}`: {e}"));
    let releases = release_metadata::parse_release_metadata_json(&json, R_VERSION_METADATA_PATH)
        .unwrap_or_else(|e| panic!("{e}"));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    fs::write(
        out_dir.join("r_version_releases.rs"),
        generated_release_metadata(&releases),
    )
    .expect("failed to write generated R release metadata");
}

fn generated_release_metadata(releases: &[release_metadata::ReleaseMetadata<'_>]) -> String {
    let mut output = String::from("// @generated by build.rs\n");
    output.push_str("const EMBEDDED_MINOR_RELEASES: &[MinorRelease] = &[\n");
    for ((major, minor), date) in embedded_minor_releases(releases) {
        output.push_str("    MinorRelease {\n");
        output.push_str("        major: ");
        output.push_str(&major.to_string());
        output.push_str(",\n");
        output.push_str("        minor: ");
        output.push_str(&minor.to_string());
        output.push_str(",\n");
        output.push_str("        date: ");
        output.push_str(&format!("{date:?}"));
        output.push_str(",\n");
        output.push_str("    },\n");
    }
    output.push_str("];\n");
    output
}

fn embedded_minor_releases<'a>(
    releases: &'a [release_metadata::ReleaseMetadata<'a>],
) -> Vec<((u64, u64), &'a str)> {
    let mut by_minor = BTreeMap::new();
    for release in releases {
        let Some((major, minor, _patch)) = version_parts(release.version.as_ref()) else {
            continue;
        };
        if major < 3 {
            continue;
        }
        let date = release.date.as_ref();
        by_minor
            .entry((major, minor))
            .and_modify(|previous: &mut &str| {
                if date < *previous {
                    *previous = date;
                }
            })
            .or_insert(date);
    }

    by_minor.into_iter().collect()
}

fn version_parts(value: &str) -> Option<(u64, u64, u64)> {
    let mut parts = value.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next()?.parse().ok()?;
    let patch = parts.next()?.parse().ok()?;
    if parts.next().is_some() {
        return None;
    }
    Some((major, minor, patch))
}
