use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

#[path = "src/rig/release_metadata.rs"]
mod release_metadata;

const R_VERSION_METADATA_FETCHED_AT_PATH: &str = "src/rig/r-versions-fetched-at.txt";
const R_VERSION_METADATA_PATH: &str = "src/rig/r-versions.json";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/rig/release_metadata.rs");
    println!("cargo:rerun-if-changed={R_VERSION_METADATA_FETCHED_AT_PATH}");
    println!("cargo:rerun-if-changed={R_VERSION_METADATA_PATH}");

    let json = fs::read_to_string(R_VERSION_METADATA_PATH)
        .unwrap_or_else(|e| panic!("failed to read `{R_VERSION_METADATA_PATH}`: {e}"));
    let releases = release_metadata::parse_release_metadata_json(&json, R_VERSION_METADATA_PATH)
        .unwrap_or_else(|e| panic!("{e}"));
    let fetched_at = fs::read_to_string(R_VERSION_METADATA_FETCHED_AT_PATH)
        .unwrap_or_else(|e| panic!("failed to read `{R_VERSION_METADATA_FETCHED_AT_PATH}`: {e}"));
    let fetched_at = parse_metadata_date(&fetched_at, R_VERSION_METADATA_FETCHED_AT_PATH)
        .unwrap_or_else(|e| panic!("{e}"));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    fs::write(
        out_dir.join("r_version_releases.rs"),
        generated_release_metadata(&releases, &fetched_at),
    )
    .expect("failed to write generated R release metadata");
}

fn generated_release_metadata(
    releases: &[release_metadata::ReleaseMetadata<'_>],
    fetched_at: &str,
) -> String {
    let mut output = String::from("// @generated by build.rs\n");
    output.push_str("const EMBEDDED_AVAILABLE_BUILD_DATE: &str = ");
    output.push_str(&format!("{fetched_at:?};\n"));
    output.push_str("const EMBEDDED_AVAILABLE: &[AvailableCandidate<'static>] = &[\n");
    for release in embedded_available_releases(releases) {
        output.push_str("    AvailableCandidate {\n");
        output.push_str("        name: ");
        output.push_str(&format!("{:?}", release.name.as_ref()));
        output.push_str(",\n");
        output.push_str("        version: ");
        output.push_str(&format!("{:?}", release.version.as_ref()));
        output.push_str(",\n");
        output.push_str("        date: Some(");
        output.push_str(&format!("{:?}", release.date.as_ref()));
        output.push_str("),\n");
        output.push_str("    },\n");
    }
    output.push_str("];\n");
    output
}

fn embedded_available_releases<'a>(
    releases: &'a [release_metadata::ReleaseMetadata<'a>],
) -> Vec<&'a release_metadata::ReleaseMetadata<'a>> {
    let mut by_minor: BTreeMap<(u64, u64), &release_metadata::ReleaseMetadata<'_>> =
        BTreeMap::new();
    for release in releases {
        let Some((major, minor, patch)) = version_parts(release.version.as_ref()) else {
            continue;
        };
        if major < 4 || (major == 4 && minor < 1) {
            continue;
        }
        let key = (major, minor);
        if by_minor
            .get(&key)
            .and_then(|previous| version_parts(previous.version.as_ref()))
            .map(|(_, _, previous_patch)| patch > previous_patch)
            .unwrap_or(true)
        {
            by_minor.insert(key, release);
        }
    }

    by_minor.into_values().collect()
}

fn version_parts(value: &str) -> Option<(u64, u64, u64)> {
    let mut parts = value.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next()?.parse().ok()?;
    let patch = parts.next()?.parse().ok()?;
    if parts.next().is_some() {
        return None;
    }
    Some((major, minor, patch))
}

fn parse_metadata_date(value: &str, source: &str) -> Result<String, String> {
    let value = value.trim();
    if !is_iso_date(value) {
        return Err(format!(
            "R version availability metadata date in {source} must be in YYYY-MM-DD format"
        ));
    }
    Ok(value.to_string())
}

fn is_iso_date(value: &str) -> bool {
    let bytes = value.as_bytes();
    bytes.len() == 10
        && bytes[0].is_ascii_digit()
        && bytes[1].is_ascii_digit()
        && bytes[2].is_ascii_digit()
        && bytes[3].is_ascii_digit()
        && bytes[4] == b'-'
        && bytes[5].is_ascii_digit()
        && bytes[6].is_ascii_digit()
        && bytes[7] == b'-'
        && bytes[8].is_ascii_digit()
        && bytes[9].is_ascii_digit()
}
