use std::env;
use std::fs;
use std::path::PathBuf;

#[path = "src/rig/release_metadata.rs"]
mod release_metadata;

const R_VERSION_METADATA_FETCHED_AT_PATH: &str = "src/rig/r-versions-fetched-at.txt";
const R_VERSION_METADATA_PATH: &str = "src/rig/r-versions.json";
const R_VERSION_METADATA_TARGET_PATH: &str = "src/rig/r-versions-target.txt";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/rig/release_metadata.rs");
    println!("cargo:rerun-if-changed={R_VERSION_METADATA_FETCHED_AT_PATH}");
    println!("cargo:rerun-if-changed={R_VERSION_METADATA_PATH}");
    println!("cargo:rerun-if-changed={R_VERSION_METADATA_TARGET_PATH}");

    let json = fs::read_to_string(R_VERSION_METADATA_PATH)
        .unwrap_or_else(|e| panic!("failed to read `{R_VERSION_METADATA_PATH}`: {e}"));
    let releases = release_metadata::parse_release_metadata_json(&json, R_VERSION_METADATA_PATH)
        .unwrap_or_else(|e| panic!("{e}"));
    let has_install_urls = release_metadata_json_has_install_urls(&json, R_VERSION_METADATA_PATH)
        .unwrap_or_else(|e| panic!("{e}"));
    let metadata_date = fs::read_to_string(R_VERSION_METADATA_FETCHED_AT_PATH)
        .unwrap_or_else(|e| panic!("failed to read `{R_VERSION_METADATA_FETCHED_AT_PATH}`: {e}"));
    let metadata_date = parse_metadata_date(&metadata_date, R_VERSION_METADATA_FETCHED_AT_PATH)
        .unwrap_or_else(|e| panic!("{e}"));
    let metadata_target = fs::read_to_string(R_VERSION_METADATA_TARGET_PATH)
        .unwrap_or_else(|e| panic!("failed to read `{R_VERSION_METADATA_TARGET_PATH}`: {e}"));
    let metadata_target = parse_metadata_target(&metadata_target, R_VERSION_METADATA_TARGET_PATH)
        .unwrap_or_else(|e| panic!("{e}"));
    if metadata_target.is_some() && !has_install_urls {
        panic!("R version availability metadata with a target must come from `rig available --json --all`");
    }
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    fs::write(
        out_dir.join("r_version_releases.rs"),
        generated_releases(&releases, &metadata_date, metadata_target.as_deref()),
    )
    .expect("failed to write generated R release metadata");
}

fn generated_releases(
    releases: &[release_metadata::ReleaseMetadata<'_>],
    metadata_date: &str,
    metadata_target: Option<&str>,
) -> String {
    let mut output = String::from("// @generated by build.rs\n");
    output.push_str("pub(crate) const EMBEDDED_AVAILABLE_METADATA_DATE: &str = ");
    output.push_str(&format!("{metadata_date:?};\n"));
    output.push_str("pub(crate) const EMBEDDED_AVAILABLE_METADATA_TARGET: Option<&str> = ");
    match metadata_target {
        Some(target) => output.push_str(&format!("Some({target:?});\n")),
        None => output.push_str("None;\n"),
    }
    output.push_str("pub(crate) const EMBEDDED_R_RELEASES: &[ReleaseMetadata<'static>] = &[\n");
    for release in releases {
        output.push_str("    ReleaseMetadata {\n");
        output.push_str("        name: std::borrow::Cow::Borrowed(");
        output.push_str(&format!("{:?}", release.name.as_ref()));
        output.push_str("),\n");
        output.push_str("        version: std::borrow::Cow::Borrowed(");
        output.push_str(&format!("{:?}", release.version.as_ref()));
        output.push_str("),\n");
        output.push_str("        date: std::borrow::Cow::Borrowed(");
        output.push_str(&format!("{:?}", release.date.as_ref()));
        output.push_str("),\n");
        output.push_str("    },\n");
    }
    output.push_str("];\n");
    output
}

#[derive(serde::Deserialize)]
struct ReleaseMetadataTargetCheck {
    #[serde(default)]
    url: Option<String>,
}

fn release_metadata_json_has_install_urls(json: &str, source: &str) -> Result<bool, String> {
    let versions: Vec<ReleaseMetadataTargetCheck> =
        serde_json::from_str(json).map_err(|e| format!("failed to parse {source} JSON: {e}"))?;
    Ok(versions
        .iter()
        .any(|version| version.url.as_deref().is_some_and(|url| !url.is_empty())))
}

fn parse_metadata_target(value: &str, source: &str) -> Result<Option<String>, String> {
    let value = value.trim();
    if value == "neutral" {
        return Ok(None);
    }
    let Some((platform, arch)) = value.split_once('/') else {
        return Err(format!(
            "R version availability metadata target in {source} must be `neutral` or `<platform>/<arch>`"
        ));
    };
    if platform.is_empty()
        || arch.is_empty()
        || value.chars().any(char::is_whitespace)
        || arch.contains('/')
    {
        return Err(format!(
            "R version availability metadata target in {source} must be `neutral` or `<platform>/<arch>`"
        ));
    }
    Ok(Some(value.to_string()))
}

fn parse_metadata_date(value: &str, source: &str) -> Result<String, String> {
    let value = value.trim();
    if !is_iso_date(value) {
        return Err(format!(
            "R version availability metadata date in {source} must be in YYYY-MM-DD format"
        ));
    }
    Ok(value.to_string())
}

fn is_iso_date(value: &str) -> bool {
    let bytes = value.as_bytes();
    bytes.len() == 10
        && bytes[0].is_ascii_digit()
        && bytes[1].is_ascii_digit()
        && bytes[2].is_ascii_digit()
        && bytes[3].is_ascii_digit()
        && bytes[4] == b'-'
        && bytes[5].is_ascii_digit()
        && bytes[6].is_ascii_digit()
        && bytes[7] == b'-'
        && bytes[8].is_ascii_digit()
        && bytes[9].is_ascii_digit()
}
