use std::error::Error;

use super::r_selection;
use super::rig_client;

// Generated by build.rs from src/rig/r-versions.json:
// - EMBEDDED_MINOR_RELEASES_FETCHED_AT: &str
// - EMBEDDED_MINOR_RELEASES: &[RMinorRelease<'static>]
include!(concat!(env!("OUT_DIR"), "/r_version_releases.rs"));

#[derive(Clone, Copy, Debug)]
struct RMinorRelease<'a> {
    major: u64,
    minor: u64,
    date: &'a str,
}

#[derive(serde::Deserialize)]
struct RigAvailableRelease {
    version: String,
    date: Option<String>,
}

pub(crate) fn latest_minor_version_on(exclude_newer: &str) -> Result<String, Box<dyn Error>> {
    if exclude_newer <= EMBEDDED_MINOR_RELEASES_FETCHED_AT {
        return Ok(latest_minor_release_on(
            exclude_newer,
            EMBEDDED_MINOR_RELEASES.iter().copied(),
        )?
        .version());
    }

    let available = all_available_releases()?;
    let release = latest_minor_release_on(
        exclude_newer,
        available
            .iter()
            .filter_map(|release| minor_release_from_available(release).transpose())
            .collect::<Result<Vec<_>, _>>()?,
    )?;
    Ok(release.version())
}

fn latest_minor_release_on<'a>(
    exclude_newer: &str,
    releases: impl IntoIterator<Item = RMinorRelease<'a>>,
) -> Result<RMinorRelease<'a>, Box<dyn Error>> {
    releases
        .into_iter()
        .filter(|release| release.date <= exclude_newer)
        .max_by_key(|release| (release.major, release.minor))
        .ok_or_else(|| {
            format!(
                "could not resolve latest R minor version available before or on {exclude_newer}"
            )
            .into()
        })
}

fn all_available_releases() -> Result<Vec<RigAvailableRelease>, Box<dyn Error>> {
    let json = String::from_utf8(rig_client::output(&["available", "--all", "--json"])?)
        .map_err(|e| format!("`rig available --all --json` returned non-UTF-8 output: {e}"))?;
    serde_json::from_str(&json)
        .map_err(|e| format!("failed to parse `rig available --all --json` JSON: {e}").into())
}

fn minor_release_from_available(
    release: &RigAvailableRelease,
) -> Result<Option<RMinorRelease<'_>>, Box<dyn Error>> {
    let Some((major, minor)) = minor_release_version(&release.version) else {
        return Ok(None);
    };
    let Some(date) = release.date.as_deref() else {
        return Ok(None);
    };
    let date = r_selection::iso_date_prefix(date).ok_or_else(|| {
        format!(
            "rig available returned invalid release date `{}` for R {}",
            date, release.version
        )
    })?;

    Ok(Some(RMinorRelease { major, minor, date }))
}

fn minor_release_version(version: &str) -> Option<(u64, u64)> {
    let mut parts = version.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next()?.parse().ok()?;
    let patch = parts.next()?;
    if patch != "0" || parts.next().is_some() {
        return None;
    }

    Some((major, minor))
}

impl RMinorRelease<'_> {
    fn version(&self) -> String {
        format!("{}.{}", self.major, self.minor)
    }
}
