use std::collections::BTreeMap;
use std::error::Error;

use time::{Date, Duration};

use super::rig_client::{self, InstalledR};

// Generated by build.rs from src/rig/r-versions.json:
// - EMBEDDED_MINOR_RELEASES_FETCHED_AT: &str
// - EMBEDDED_MINOR_RELEASES: &[MinorRelease]
include!(concat!(env!("OUT_DIR"), "/r_version_releases.rs"));

// R minor releases are roughly annual; keep live discovery off the hot path
// until the latest embedded minor is old enough that a new minor may exist.
const LIVE_DISCOVERY_AFTER_LATEST_MINOR_DAYS: i64 = 330;

struct MinorRelease {
    major: u64,
    minor: u64,
    date: &'static str,
}

#[derive(serde::Deserialize)]
struct AvailableRelease {
    #[serde(default)]
    name: Option<String>,
    version: String,
    date: Option<String>,
}

pub(crate) fn latest_minor_version_on(
    exclude_newer: &str,
    installed: &[InstalledR],
) -> Result<String, Box<dyn Error>> {
    let mut version = latest_embedded_minor_version_on(exclude_newer);

    if should_discover_available_minor_versions(exclude_newer, installed) {
        match latest_available_minor_version_on(exclude_newer) {
            Ok(Some(discovered)) => {
                version = Some(
                    version
                        .map(|embedded| embedded.max(discovered))
                        .unwrap_or(discovered),
                );
            }
            Ok(None) => {}
            Err(err) => return Err(err),
        }
    }

    let (major, minor) = version.ok_or_else(|| {
        format!("could not resolve latest R minor version available before or on {exclude_newer}")
    })?;

    Ok(format!("{major}.{minor}"))
}

fn latest_embedded_minor_version_on(exclude_newer: &str) -> Option<(u64, u64)> {
    EMBEDDED_MINOR_RELEASES
        .iter()
        .filter(|release| release.date <= exclude_newer)
        .max_by_key(|release| (release.major, release.minor))
        .map(|release| (release.major, release.minor))
}

fn latest_embedded_minor_version() -> Option<(u64, u64)> {
    EMBEDDED_MINOR_RELEASES
        .iter()
        .max_by_key(|release| (release.major, release.minor))
        .map(|release| (release.major, release.minor))
}

fn latest_embedded_minor_release_date() -> Option<&'static str> {
    EMBEDDED_MINOR_RELEASES
        .iter()
        .max_by_key(|release| (release.major, release.minor))
        .map(|release| release.date)
}

fn should_discover_available_minor_versions(exclude_newer: &str, installed: &[InstalledR]) -> bool {
    exclude_newer > EMBEDDED_MINOR_RELEASES_FETCHED_AT
        && (installed_has_minor_after_embedded_metadata(installed)
            || embedded_minor_metadata_is_stale_for(exclude_newer))
}

fn installed_has_minor_after_embedded_metadata(installed: &[InstalledR]) -> bool {
    let Some(latest_embedded) = latest_embedded_minor_version() else {
        return true;
    };

    installed
        .iter()
        .filter(|installed| {
            !matches!(installed.name.as_str(), "devel" | "next")
                && !installed
                    .aliases
                    .iter()
                    .any(|alias| matches!(alias.as_str(), "devel" | "next"))
        })
        .filter_map(|installed| {
            version_parts(&installed.version).map(|(major, minor, _patch)| (major, minor))
        })
        .any(|version| version > latest_embedded)
}

fn embedded_minor_metadata_is_stale_for(exclude_newer: &str) -> bool {
    let Some(latest_date) = latest_embedded_minor_release_date() else {
        return true;
    };
    let Some(latest_date) = parse_iso_date(latest_date) else {
        return true;
    };
    let Some(exclude_newer) = parse_iso_date(exclude_newer) else {
        return true;
    };

    exclude_newer >= latest_date + Duration::days(LIVE_DISCOVERY_AFTER_LATEST_MINOR_DAYS)
}

fn latest_available_minor_version_on(
    exclude_newer: &str,
) -> Result<Option<(u64, u64)>, Box<dyn Error>> {
    let json = String::from_utf8(rig_client::output(&["available", "--all", "--json"])?)
        .map_err(|e| format!("`rig available --all --json` returned non-UTF-8 output: {e}"))?;
    let available: Vec<AvailableRelease> = serde_json::from_str(&json)
        .map_err(|e| format!("failed to parse `rig available --all --json` JSON: {e}"))?;

    let mut first_release_dates = BTreeMap::new();
    for release in available {
        if matches!(release.name.as_deref(), Some("devel" | "next")) {
            continue;
        }
        let Some((major, minor, _patch)) = version_parts(&release.version) else {
            continue;
        };
        if major < 3 {
            continue;
        }
        let Some(date) = release.date.as_deref().and_then(iso_date_prefix) else {
            continue;
        };
        first_release_dates
            .entry((major, minor))
            .and_modify(|previous: &mut String| {
                if date < previous.as_str() {
                    *previous = date.to_string();
                }
            })
            .or_insert_with(|| date.to_string());
    }

    Ok(first_release_dates
        .into_iter()
        .filter(|(_, date)| date.as_str() <= exclude_newer)
        .map(|(version, _)| version)
        .max())
}

fn version_parts(value: &str) -> Option<(u64, u64, u64)> {
    let mut parts = value.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next()?.parse().ok()?;
    let patch = parts.next()?.parse().ok()?;
    if parts.next().is_some() {
        return None;
    }
    Some((major, minor, patch))
}

fn parse_iso_date(value: &str) -> Option<Date> {
    let format = time::macros::format_description!("[year]-[month]-[day]");
    Date::parse(value, &format).ok()
}

fn iso_date_prefix(value: &str) -> Option<&str> {
    let date = value.get(..10)?;
    if is_iso_date(date) {
        Some(date)
    } else {
        None
    }
}

fn is_iso_date(value: &str) -> bool {
    let bytes = value.as_bytes();
    bytes.len() == 10
        && bytes[0].is_ascii_digit()
        && bytes[1].is_ascii_digit()
        && bytes[2].is_ascii_digit()
        && bytes[3].is_ascii_digit()
        && bytes[4] == b'-'
        && bytes[5].is_ascii_digit()
        && bytes[6].is_ascii_digit()
        && bytes[7] == b'-'
        && bytes[8].is_ascii_digit()
        && bytes[9].is_ascii_digit()
}
